package main

import (
	"flag"
	"log/slog"
	"os"
	"runtime/pprof"
	"strings"
)

func main() {
	var (
		cpuProfile = flag.String("cpuprofile", "cpu.prof", "write CPU profile to file")
		iterations = flag.Int("iterations", 60_000, "number of iterations")
	)
	flag.Parse()

	file, err := os.Create(*cpuProfile)
	if err != nil {
		slog.Error("create profile", "error", err)
		os.Exit(1)
	}
	defer file.Close()

	if err := pprof.StartCPUProfile(file); err != nil {
		slog.Error("start cpu profile", "error", err)
		os.Exit(1)
	}
	defer pprof.StopCPUProfile()
/////////////////////////////////////
	total := 0
	for i := 0; i < *iterations; i++ {
		total += expensiveWork(i)
	}

	slog.Info("cpu profiling finished", "iterations", *iterations, "result", total, "profile", *cpuProfile)
}

func expensiveWork(seed int) int {
	parts := make([]string, 0, 200)
	for i := 0; i < 200; i++ {
		parts = append(parts, strings.Repeat(string(rune('a'+(seed+i)%26)), 25))
	}

	joined := strings.Join(parts, "")
	score := 0
	for _, r := range joined {
		score += int(r)
	}
	return score
}

/*Explain the output of the CPU profile generated by this program. What does it tell us about the performance of the `expensiveWork` function? How can we use this information to optimize our code?*/
/*
   Showing top 10 nodes out of 87
      flat  flat%   sum%        cum   cum%
    1130ms 39.37% 39.37%     1130ms 39.37%  hour17-benchmarking.SumInts
     320ms 11.15% 50.52%      770ms 26.83%  strings.(*Builder).WriteString
     160ms  5.57% 56.10%      160ms  5.57%  runtime.memmove
     160ms  5.57% 61.67%      170ms  5.92%  runtime.preemptM
     110ms  3.83% 65.51%      120ms  4.18%  runtime.typePointers.next
     100ms  3.48% 68.99%      260ms  9.06%  runtime.scanObject
      90ms  3.14% 72.13%       90ms  3.14%  runtime.semasleep
      70ms  2.44% 74.56%       70ms  2.44%  runtime.memclrNoHeapPointers
      70ms  2.44% 77.00%       70ms  2.44%  runtime.sysUnusedOS
      70ms  2.44% 79.44%       70ms  2.44%  strings.(*Builder).copyCheck (inline)
(pprof) 
*/
//The CPU profile output indicates that the `expensiveWork` function is the most time-consuming part of the program, accounting for 39.37% of the total CPU time. This suggests that the operations within `expensiveWork`, such as string manipulation and building, are likely the bottlenecks in terms of performance.

//To optimize the code, we can focus on improving the efficiency of the `expensiveWork` function. One potential optimization could be to reduce the number of string concatenations, as they can be costly in terms of performance. Instead of using `strings.Join`, we could consider using a more efficient method for building the string, such as using a `bytes.Buffer` or preallocating a slice of bytes to avoid unnecessary allocations.

//Additionally, we can analyze the specific operations within `expensiveWork` that are contributing to the high CPU usage and look for ways to optimize those operations, such as reducing the number of iterations or simplifying the logic used to generate the strings.
//Overall, the CPU profile provides valuable insights into where the program is spending most of its time, allowing us to target our optimization efforts effectively.
//need head wise description of the output of the CPU profile generated by this program. What does it tell us about the performance of the `expensiveWork` function? How can we use this information to optimize our code?
/*
The CPU profile output provides a breakdown of the time spent in various functions during the execution of the program. The key points from the profile are as follows:
	
1. **`hour17-benchmarking.SumInts`**: This function is the most time-consuming, accounting for 39.37% of the total CPU time. This indicates that a significant portion of the program's execution time is spent in this function, which is likely called within `expensiveWork`.	
	
2. **`strings.(*Builder).WriteString`**: This function accounts for 11.15% of the CPU time, suggesting that string building operations are a significant part of the performance bottleneck.

3. **`runtime.memmove`**: This function accounts for 5.57% of the CPU time, indicating that memory copying operations are also contributing to the performance issues.

4. **Other runtime functions**: Functions like `runtime.preemptM`, `runtime.typePointers.next`, `runtime.scanObject`, and `runtime.semasleep` also contribute to the CPU time, but to a lesser extent.

Overall, the profile indicates that the `expensiveWork` function is a major contributor to the CPU usage, primarily due to string manipulation and building operations. To optimize the code, we can focus on reducing the number of string concatenations and improving the efficiency of string building, potentially by using more efficient data structures or algorithms for string manipulation. Additionally, analyzing and optimizing memory usage could also help improve performance.	
*/
/*Need each heading wise description of the output of the CPU profile generated by this program. What does it tell us about the performance of the `expensiveWork` function? How can we use this information to optimize our code?*/
/*
1. **`hour17-benchmarking.SumInts`**: This function is the most time-consuming, accounting for 39.37% of the total CPU time. This indicates that a significant portion of the program's execution time is spent in this function, which is likely called within `expensiveWork`. This suggests that the logic within `SumInts` may be inefficient and could be a target for optimization.

2. **`strings.(*Builder).WriteString`**: This function accounts for 11.15% of the CPU time, suggesting that string building operations are a significant part of the performance bottleneck. This indicates that the way strings are being constructed in `expensiveWork` may be inefficient, and optimizing this part of the code could lead to performance improvements.

3. **`runtime.memmove`**: This function accounts for 5.57% of the CPU time, indicating that memory copying operations are also contributing to the performance issues. This suggests that there may be inefficient memory usage in the program, and optimizing memory management could help reduce CPU time.

4. **Other runtime functions**: Functions like `runtime.preemptM`, `runtime.typePointers.next`, `runtime.scanObject`, and `runtime.semasleep` also contribute to the CPU time, but to a lesser extent. These functions are part of the Go runtime and may indicate that there are some blocking operations or garbage collection activities happening during the execution of the program.

Overall, the profile indicates that the `expensiveWork` function is a major contributor to the CPU usage, primarily due to string manipulation and building operations. To optimize the code, we can focus on reducing the number of string concatenations and improving the efficiency of string building, potentially by using more efficient data structures or algorithms for string manipulation. Additionally, analyzing and optimizing memory usage could also help improve performance.
*/


